# Generated by Django 4.2.7 on 2023-11-27 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnteredImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_file', models.FileField(blank=True, null=True, upload_to='enteredImages/')),
            ],
        ),
        migrations.CreateModel(
            name='FilteredImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_file', models.FileField(upload_to='filteredImages/')),
                ('filter_used', models.CharField(max_length=255)),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detections.enteredimage')),
            ],
        ),
    ]
